name: Blog de gnidmoo
url: http://example.org
description: Programmation C++ et projets en cours

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

